// <auto-generated />
namespace Pedidos.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Crearbasededatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Crearbasededatos));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081501312_Crear base de datos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
